[project]
name = "myresume"
version = "0.1.0"
description = "Resume built using Rendercv."
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["bs4>=0.0.2", "pyyaml>=6.0.2", "rendercv[full]>=2.2"]
